version: '3.3'

services: 
  web:
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
      - 8000:8000
    depends_on: 
      - db
    environment: 
      - "DJANGO_SECRET_KEY=gxeyqs4tvqr@84-9=(8m0(yxgc$fsp*iow9enw)i&t+2f$p)x$$"
      - "DJANGO_DEBUG=True"
    
  db:
    image: postgres:11
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes: 
  postgres_data:

      